### ISSUE TITLE
Handling excel files with multiple sheets

### ISSUE THREAD

**Issue by mohitpawar473** [pgalko/BambooAI#1]
How should we handle excel files with multiple sheets. I have tried and I am getting error-  list object has no attribute 'columns'

**Comment by mohitpawar473** [comment]
Handling Multiple csv files is also another question?

**Comment by pgalko** [comment]
It currently does not work with multiple sheets or CSVs by way of arguments. However, you can try to run it without the "df" argument (e.g., bamboo = BambooAI(debug=False, llm="gpt-4")) and instruct it like this:
"You have access to multiple CSVs with names doc1.csv, doc2.csv, doc3.csv, and they are located here <path>. Here is what I want to do with them: <instruction on what you want to do with them>."
It will perform the required manipulations and remember them. This approach has worked for me, but might require a several to get the prompt right.

**Comment by mohitpawar473** [comment]
Oh got it. Just a follow up question , this prompt/ instructions would go into my query everytime I run or will there be a prefix which will remember that I have multiple dataframes. Just wanted to know.

**Comment by pgalko** [comment]
You will only need to instruct it once at the beginning of the loop, and it will remember it for  subsequent prompts.

Eg.
1. Merge files
2. Load data from the merged files into data frame 
3. Do something with data frame
4. Do something else with the data frame
Etc.

However when you finish the loop/chain by typing "exit", the memory is wiped and you will need the instruct it again when you start the new loop. I hope it helps.

**Comment by mohitpawar473** [comment]
Understood. I think you are talking about the agent that works continuously and not the single execution one. Let me know if I am understanding correctly.

**Comment by pgalko** [comment]
Yes, that is correct. For single execution, you can ask it to merge the files/manipulate the data and save it as a new file. In the next execution you can use the resulting merged/manipulated file. This also reduces the token usage as previous conversations are not appended to the prompt.
